spring:
  application:
    name: receipt-${server.port}
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/receipt?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: receipt
    password: 123456

server:
  port: 10001


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bmilk.receipt.entry


logging:
  file:
    path: ./log/
    name: ${spring.application.name}.log
  level:
    root: info
    com.bmilk.receipt.dao: trace

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:${eureka.server.port}/eureka
    register-with-eureka: true
  server:
    port: 7001